import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b bg-teal-50 text-teal-900">
          <nav className="mx-auto max-w-5xl p-4 flex gap-4">
            <a href="/" className="font-semibold hover:underline">Home</a>
            <a href="/categories" className="hover:underline">Categories</a>
          </nav>
        </header>
        {children}
        <SpeedInsights/>
      </body>
    </html>
  );
}
